cc_binary(
    name = "pathexists",
    srcs = ["examples/pathexists.cc"],
    deps = ["//base"],
)

cc_binary(
    name = "absolutepath",
    srcs = ["examples/absolutepath.cc"],
    deps = ["//base"],
)
