.TH ECHOD "8" "Echo Daemon" "August 1, 2016" "Echo Daemon"

.SH NAME
echod \- Echo daemon

.SH SYNOPSIS
\fBechod\fR [\fIOPTIONS\fR...]

.SH DESCRIPTION
\fBechod\fR is an Echo Protocol daemon.

.SH OPTIONS
.TP
\fB\-C\fR, \fB\-\-config=\fR<file>
specify an alternative configuration file
.TP
\fB\-P\fR, \fB\-\-pidfile=\fR<file>
write process id to the specified file
.TP
\fB\-u\fR, \fB\-\-user=\fR<username>
run the daemon as user
.TP
\fB\-a\fR, \fB\-\-address=\fR<ip/domain>
bind to the specified address
.TP
\fB\-p\fR, \fB\-\-port=\fR<number>
TCP port to listen on
.TP
\fB\-b\fR, \fB\-\-backlog=\fR<number>
set the backlog queue limit
.TP
\fB\-f\fR, \fB\-\-foreground\fR
run the daemon in the foreground
.TP
\fB\-L\fR, \fB\-\-logfile=\fR<file>
write log messages to the specified file
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-V\fR, \fB\-\-version\fR
output version information and exit

.SH "SEE ALSO"
\fBecho\fR(1), \fBechod.conf\fR(5)
