.TH echod "8" "Echo Daemon" "August 1, 2016" "Echo Daemon"

.SH "NAME"
echod \- Echo daemon

.SH "SYNOPSIS"
\fBechod\fR [\fOPTIONS\fR...]

.SH "DESCRIPTION"
\fBechod\fR is an Echo Protocol daemon.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Show usage information and exit.

.TP
\fB\-d\fR, \fB\-\-daemonize\fR
Run as a daemon.

.TP
\fB\-p\fR, \fB\-\-port=\fIport\fP
Set the tcp \fIport\fP to listen on. (default: 7)

.SH "SEE ALSO"
\fBecho\fR(1), \fBechod.conf\fR(5)
