.TH ECHOD 8 "August 1, 2016"
.SH NAME
echod \- Echo daemon
.SH SYNOPSIS
.B echod
.RI [ options ]
.SH DESCRIPTION
\fBechod\fP is an Echo Protocol daemon.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Show usage information and exit.
.TP
.BR \-d ", " \-\-daemonize
Run as a daemon.
.TP
.BR \-p ", " \-\-port=\fIport\fP
Set the tcp \fIport\fP to listen on. (default: 7)
.SH SEE ALSO
.BR echo (1)
